# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# To use this formula, create a repository named "homebrew-ipb" on GitHub
# and place this file in Formula/ipb.rb
#
# Installation:
#   brew tap devinpearson/ipb
#   brew install ipb
#
# Or install directly:
#   brew install devinpearson/ipb/ipb

class Ipb < Formula
  desc "CLI application to manage programmable banking cards"
  homepage "https://github.com/devinpearson/ipb"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devinpearson/ipb/releases/download/v#{version}/ipb-macos-arm64"
      # Calculate SHA256: shasum -a 256 dist/ipb-macos-arm64
      sha256 "REPLACE_WITH_ACTUAL_SHA256_CHECKSUM"

      def install
        bin.install "ipb-macos-arm64" => "ipb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinpearson/ipb/releases/download/v#{version}/ipb-macos-x64"
      # Calculate SHA256: shasum -a 256 dist/ipb-macos-x64
      sha256 "REPLACE_WITH_ACTUAL_SHA256_CHECKSUM"

      def install
        bin.install "ipb-macos-x64" => "ipb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/devinpearson/ipb/releases/download/v#{version}/ipb-linux-arm64"
      # Calculate SHA256: shasum -a 256 dist/ipb-linux-arm64
      sha256 "REPLACE_WITH_ACTUAL_SHA256_CHECKSUM"

      def install
        bin.install "ipb-linux-arm64" => "ipb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devinpearson/ipb/releases/download/v#{version}/ipb-linux-x64"
      # Calculate SHA256: shasum -a 256 dist/ipb-linux-x64
      sha256 "REPLACE_WITH_ACTUAL_SHA256_CHECKSUM"

      def install
        bin.install "ipb-linux-x64" => "ipb"
      end
    end
  end

  test do
    system "#{bin}/ipb", "--version"
  end
end

