#!/usr/bin/env bash
export DEBUG=true
vhs tapes/cards.tape
vhs tapes/deploy.tape
vhs tapes/env.tape
vhs tapes/fetch.tape
vhs tapes/logs.tape
vhs tapes/new.tape
vhs tapes/publish.tape
vhs tapes/published.tape
vhs tapes/run.tape
vhs tapes/simulate.tape
vhs tapes/toggle.tape
vhs tapes/upload-env.tape
vhs tapes/upload.tape
